### ISSUE TITLE
[Question] running TPC-H with test:run

### ISSUE THREAD

**Issue by bmyerz** [epfldata/dblab#45]
I'm trying to run the `test:run` target.

I have TPC-H scale 1 generated tables in a directory called `/path/to/tpc/dbgen/sf1`.
I am running the following in sbt.

`test:run /path/to/tpc/dbgen 1 Q1`

I get the following error, which I assume has to do with the command line arguments. Am I running it incorrectly?

```
[error] (run-main) java.lang.NumberFormatException: For input string: ""
java.lang.NumberFormatException: For input string: ""
        at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
        at java.lang.Integer.parseInt(Integer.java:504)
        at java.lang.Integer.parseInt(Integer.java:527)
        at ch.epfl.data.legobase.storagemanager.Loader$.fileLineCount(Loader.scala:46)
        at ch.epfl.data.legobase.Q1$.main(Q1_Generated.scala:30)
```

**Comment by amirsh** [comment]
Please refer to the new documentation on how to run queries in both interpretation and compilation modes.
