### ISSUE TITLE
LegoBaseScanner: Reading 'null' values leads to exception

### ISSUE THREAD

**Issue by flock0** [epfldata/dblab#58]
When trying to read values from  a `.tbl` file with LegobaseScanner and one of the attributes of a row is not set (by having two delimiters `||` one after another), an exception gets thrown.

To reproduce the problem:
The call_center table of the TPC-DS dataset, which can be found on the testserver in `/mnt/ramdisk/tpcds/linebreaks/sf1/call_center.tbl` contains null values in the first row. A simple query like `SELECT COUNT(*) AS cnt FROM call_center` leads to the following exception:

```
[error] (run-main-0) java.lang.RuntimeException: Tried to read Integer, but found neither delimiter nor . after number (found |, previous token = 0/0)
java.lang.RuntimeException: Tried to read Integer, but found neither delimiter nor . after number (found |, previous token = 0/0)
    at ch.epfl.data.dblab.legobase.storagemanager.LegobaseScanner.next_int(LegoBaseScanner.scala:42)
    at ch.epfl.data.dblab.legobase.storagemanager.LegobaseScanner.next_date(LegoBaseScanner.scala:87)
    at ch.epfl.data.dblab.legobase.storagemanager.Loader$$anonfun$2.apply(Loader.scala:66)
    at ch.epfl.data.dblab.legobase.storagemanager.Loader$$anonfun$2.apply(Loader.scala:61)
    at scala.collection.immutable.List.map(List.scala:276)
    at ch.epfl.data.dblab.legobase.storagemanager.Loader$.loadTable(Loader.scala:61)
    at ch.epfl.data.dblab.legobase.LegoInterpreter$.convertOperator(LegoInterpreter.scala:377)
    at ch.epfl.data.dblab.legobase.LegoInterpreter$.createAggOpOperator(LegoInterpreter.scala:323)
    at ch.epfl.data.dblab.legobase.LegoInterpreter$.convertOperator(LegoInterpreter.scala:383)
    at ch.epfl.data.dblab.legobase.LegoInterpreter$.createPrintOperator(LegoInterpreter.scala:367)
    at ch.epfl.data.dblab.legobase.LegoInterpreter$.convertOperator(LegoInterpreter.scala:389)
    at ch.epfl.data.dblab.legobase.LegoInterpreter$.executeQuery(LegoInterpreter.scala:40)
    at ch.epfl.data.dblab.legobase.LegoRunner$$anonfun$run$1$$anonfun$apply$1.apply$mcV$sp(LegoRunner.scala:86)
    at ch.epfl.data.dblab.legobase.LegoRunner$$anonfun$run$1$$anonfun$apply$1.apply(LegoRunner.scala:76)
    at ch.epfl.data.dblab.legobase.LegoRunner$$anonfun$run$1$$anonfun$apply$1.apply(LegoRunner.scala:76)
    at scala.util.DynamicVariable.withValue(DynamicVariable.scala:58)
    at scala.Console$.withOut(Console.scala:53)
    at ch.epfl.data.dblab.legobase.LegoRunner$class.run(LegoRunner.scala:74)
    at ch.epfl.data.dblab.legobase.LegoInterpreter$.run(LegoInterpreter.scala:19)
    at ch.epfl.data.dblab.legobase.LegoInterpreter$.main(LegoInterpreter.scala:30)
    at ch.epfl.data.dblab.legobase.LegoInterpreter.main(LegoInterpreter.scala)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
```

The `flock0/dblab/frontend_tpcds` branch already contains the TPC-DS schema for easy testing. Just create a .sql file with the aforementioned query in the tpcds folder and execute
`run /mnt/ramdisk/tpcds/linebreaks TPCDS 1 <x>`

Please advise on how to handle that, thanks!

**Comment by yannisklonatos** [comment]
Fixed in latest commit of frontend
