### ISSUE TITLE
LegoBaseScanner sometimes generates faulty values at line breaks in TPC-DS dataset

### ISSUE THREAD

**Issue by flock0** [epfldata/dblab#59]
When trying to read values from certain `.tbl` files from the TPC-DS dataset with LegobaseScanner, the scanner not only reads the values that are actually in the dataset (between the delimiters) but an additional zero at a line break.

To reproduce the problem:
The problem occurs for example in Q1. The `flock0/dblab/frontend_tpcds` already contains the TPC-DS schema for easy testing. Executing Q1 with `run /mnt/ramdisk/tpcds/linebreaks TPCDS 1 Q1` throws the following exception:

```
[error] (run-main-3) java.lang.RuntimeException: Tried to read Integer, but found neither delimiter nor . after number (found -, previous token = 1/0)
java.lang.RuntimeException: Tried to read Integer, but found neither delimiter nor . after number (found -, previous token = 1/0)
        at ch.epfl.data.dblab.legobase.storagemanager.LegobaseScanner.next_int(LegoBaseScanner.scala:42)
        at ch.epfl.data.dblab.legobase.storagemanager.Loader$$anonfun$2.apply(Loader.scala:63)
        at ch.epfl.data.dblab.legobase.storagemanager.Loader$$anonfun$2.apply(Loader.scala:61)
        at scala.collection.immutable.List.map(List.scala:276)
        at ch.epfl.data.dblab.legobase.storagemanager.Loader$.loadTable(Loader.scala:61)
        at ch.epfl.data.dblab.legobase.LegoInterpreter$.convertOperator(LegoInterpreter.scala:377)
        at ch.epfl.data.dblab.legobase.LegoInterpreter$.createJoinOperator(LegoInterpreter.scala:259)
        at ch.epfl.data.dblab.legobase.LegoInterpreter$.convertOperator(LegoInterpreter.scala:381)
        at ch.epfl.data.dblab.legobase.LegoInterpreter$.createJoinOperator(LegoInterpreter.scala:258)
        at ch.epfl.data.dblab.legobase.LegoInterpreter$.convertOperator(LegoInterpreter.scala:381)
        at ch.epfl.data.dblab.legobase.LegoInterpreter$.createJoinOperator(LegoInterpreter.scala:258)
        at ch.epfl.data.dblab.legobase.LegoInterpreter$.convertOperator(LegoInterpreter.scala:381)
        at ch.epfl.data.dblab.legobase.LegoInterpreter$.createSelectOperator(LegoInterpreter.scala:327)
        at ch.epfl.data.dblab.legobase.LegoInterpreter$.convertOperator(LegoInterpreter.scala:379)
        at ch.epfl.data.dblab.legobase.LegoInterpreter$.createAggOpOperator(LegoInterpreter.scala:323)
        at ch.epfl.data.dblab.legobase.LegoInterpreter$.convertOperator(LegoInterpreter.scala:383)
        at ch.epfl.data.dblab.legobase.LegoInterpreter$.createSortOperator(LegoInterpreter.scala:343)
        at ch.epfl.data.dblab.legobase.LegoInterpreter$.convertOperator(LegoInterpreter.scala:387)
        at ch.epfl.data.dblab.legobase.LegoInterpreter$.createPrintOperator(LegoInterpreter.scala:367)
        at ch.epfl.data.dblab.legobase.LegoInterpreter$.convertOperator(LegoInterpreter.scala:389)
        at ch.epfl.data.dblab.legobase.LegoInterpreter$.executeQuery(LegoInterpreter.scala:40)
        at ch.epfl.data.dblab.legobase.LegoRunner$$anonfun$run$1$$anonfun$apply$1.apply$mcV$sp(LegoRunner.scala:86)
        at ch.epfl.data.dblab.legobase.LegoRunner$$anonfun$run$1$$anonfun$apply$1.apply(LegoRunner.scala:76)
        at ch.epfl.data.dblab.legobase.LegoRunner$$anonfun$run$1$$anonfun$apply$1.apply(LegoRunner.scala:76)
        at scala.util.DynamicVariable.withValue(DynamicVariable.scala:58)
        at scala.Console$.withOut(Console.scala:53)
        at ch.epfl.data.dblab.legobase.LegoRunner$class.run(LegoRunner.scala:74)
        at ch.epfl.data.dblab.legobase.LegoInterpreter$.run(LegoInterpreter.scala:19)
        at ch.epfl.data.dblab.legobase.LegoInterpreter$.main(LegoInterpreter.scala:30)
        at ch.epfl.data.dblab.legobase.LegoInterpreter.main(LegoInterpreter.scala)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
```

Apparently the `store_sales` table loads without problem, but `household_demographics` shows the problem. With additional debug output, I found out that the `next_int()` call for primary key `hd_demo_sk` of the second row returns 0, but it should be 2. With that additional value inserted, the `next_int()` call for `hd_dep_count` actually reads the non-numeric `0-500` and thus throws the exception.

**Comment by flock0** [comment]
Mitigated the problem by removing the trailing delimiter characters from each line in the input files.
